global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "generator"
    static_configs:
      - targets: ["generator:9100"]

  - job_name: "auth_service"
    static_configs:
      - targets: ["auth_service:9200"]
