version: "3.9"

services:

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"

  generator:
    build:
      context: ../data_generator
      dockerfile: Dockerfile.generator
    container_name: generator
    depends_on:
      - postgres_db
    ports:
      - "9100:9100"

  auth_service:
    build:
      context: ../auth_service
      dockerfile: Dockerfile.auth
    container_name: auth_service
    ports:
      - "5005:5005"
      - "9200:9200"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9099:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3030:3000"
